#ifndef CONFIG_H
#define CONFIG_H

#define LOGGER_RING_BUF_SIZE 1024 // Must be a power of 2
#define LOGGER_MSG_PER_PAGE 5
#define LOGGER_SECTOR_ERASE_TIME 450
#define LOGGER_WRITE_EN_TIME 5
#define LOGGER_NUM_SECTORS 10
#define LOGGER_NUM_PAGES 30

#define GYRO_OFF_X 0.00795f
#define GYRO_OFF_Y -0.00295f
#define GYRO_OFF_Z 0.0002f

#endif // CONFIG_H
